Get rid of CI Shell scripts (#249)
* Inline `run-tests` in CI workflow

* Inline `build-haddock` in deploy workflow

* Factorise `nix develop`

* Remove `hlint.yaml`

* Apply suggestion from @gabrielhdt

Co-authored-by: Gabriel Hondet <7418676+gabrielhdt@users.noreply.github.com>

* `>>` > `>`

---------

Co-authored-by: Gabriel Hondet <7418676+gabrielhdt@users.noreply.github.com>

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -108,12 +108,53 @@ jobs:
           key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
           restore-keys: ${{ runner.os }}-
 
+      ## Steps below run a certain program and creates two files:
+      ## `${proj}-${step}.res` and `${proj}-${step}.out`. The former contains a
+      ## string encoding the return code of the tool whereas the latter contains
+      ## a human-readable description of what happened.
+      ##
+      ## The point of this is that we will execute these steps but we "succeed"
+      ## iff the build is ok. Another job will then check the resulting files
+      ## for their exit codes. This is ugly but it ensures that the `cabal
+      ## build` gets cached even if tests fail, which means we save a lot of
+      ## time (and CI runner money) in the long run.
+      ##
       - name: Build and run tests
         run: |
-          nix develop .#ci --command cabal update
-          nix develop .#ci --command bash ci/run-tests.sh --ci
+          nix develop .#ci --command bash -c '
+            set -xuo
 
-      - name: Upload tests output
+            cabal update
+
+            cabal_builds_all_ok=true
+
+            for proj in examples cooked-validators; do
+              pushd "$proj" || exit
+
+              echo "Running `cabal build` on $proj"
+              cabal_res=0
+              cabal build | tee "../${proj}-cabal-build.out"
+              cabal_res=$?
+              echo "cabal_build:$cabal_res" > "../${proj}-cabal-build.res"
+              if [ $cabal_res -ne 0 ]; then
+                cabal_builds_all_ok=false
+              fi
+
+              echo "Running `cabal run tests` on $proj"
+              cabal_res=0
+              cabal run tests | tee "../${proj}-cabal-test.out"
+              cabal_res=$?
+              echo "run_cabal_test:$cabal_res" > "../${proj}-cabal-test.res"
+
+              popd || exit
+            done
+
+            if ! $cabal_builds_all_ok; then
+              exit 1
+            fi
+          '
+
+      - name: Upload build and test outputs
         uses: actions/upload-artifact@v3
         with:
           name: plutus-libs-checks
@@ -128,7 +169,7 @@ jobs:
     needs: build-and-test
 
     steps:
-      - name: Accessing tests output
+      - name: Access build and test outputs
         uses: actions/download-artifact@v3
         with:
           name: plutus-libs-checks
@@ -136,12 +177,13 @@ jobs:
       - name: Check tests output
         run: |
           is_ok=true
-          for proj in "examples" "cooked-validators"; do
-            for step in "cabal-build" "cabal-test"; do
+
+          for proj in examples cooked-validators; do
+            for step in cabal-build cabal-test; do
               echo "!! [$proj]: output from $step"
               cat $proj-$step.out
               res=$(cat $proj-$step.res | cut -d':' -f2)
-              if [[ "$res" != "0" ]]; then
+              if [ "$res" -ne 0 ]; then
                 is_ok=false
               fi
             done
@@ -150,7 +192,7 @@ jobs:
           ## Because there will be a lot of tests, we print a summary of the
           ## results
           echo "Summary of results (1 is failure)"
-          for proj in "examples" "cooked-validators"; do
+          for proj in examples cooked-validators; do
             echo "Summary for: $proj"
             cat ${proj}-*.res
           done
